'use client';

import {
  CurrencyRupeeIcon,
    BoltIcon,
      ChartBarIcon,
        ExclamationCircleIcon,
        } from '@heroicons/react/24/outline';
        import Link from 'next/link';

        // Reusable Stat Card Component
        export function StatCard({ stat }) {
          return (
              <Link
                    href={stat.href}
                          className="bg-white overflow-hidden shadow rounded-lg hover:shadow-md transition-shadow"
                              >
                                    <div className="p-5">
                                            <div className="flex items-center">
                                                      <div className="flex-shrink-0">
                                                                  <stat.icon className="h-6 w-6 text-gray-400" />
                                                                            </div>
                                                                                      <div className="ml-5 w-0 flex-1">
                                                                                                  <dl>
                                                                                                                <dt className="text-sm font-medium text-gray-500 truncate">
                                                                                                                                {stat.name}
                                                                                                                                              </dt>
                                                                                                                                                            <dd>
                                                                                                                                                                            <div className="text-lg font-medium text-gray-900">
                                                                                                                                                                                              {stat.value}
                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                            </dd>
                                                                                                                                                                                                                                        </dl>
                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                      <div className="bg-gray-50 px-5 py-3">
                                                                                                                                                                                                                                                                              <div className="text-sm">
                                                                                                                                                                                                                                                                                        {stat.changeType === 'positive' && (
                                                                                                                                                                                                                                                                                                    <span className="text-green-600">{stat.change}</span>
                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                        {stat.changeType === 'negative' && (
                                                                                                                                                                                                                                                                                                                                    <span className="text-red-600">{stat.change}</span>
                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                        {stat.changeType === 'neutral' && (
                                                                                                                                                                                                                                                                                                                                                                    <span className="text-gray-600">{stat.change}</span>
                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                  // Reusable Quick Actions Component
                                                                                                                                                                                                                                                                                                                                                                                                  export function QuickActions({ actions }) {
                                                                                                                                                                                                                                                                                                                                                                                                    return (
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-white shadow rounded-lg">
                                                                                                                                                                                                                                                                                                                                                                                                              <div className="px-6 py-5 border-b border-gray-200">
                                                                                                                                                                                                                                                                                                                                                                                                                      <h3 className="text-lg font-medium leading-6 text-gray-900">
                                                                                                                                                                                                                                                                                                                                                                                                                                Quick Actions
                                                                                                                                                                                                                                                                                                                                                                                                                                        </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="px-6 py-5 grid grid-cols-1 gap-4 sm:grid-cols-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                            {actions.map((action) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  key={action.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              href={action.href}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className={`inline-flex items-center justify-center px-4 py-2 border text-sm font-medium rounded-md ${
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        action.primary 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ? 'border-transparent text-white bg-blue-600 hover:bg-blue-700'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        : 'border-gray-300 text-gray-700 bg-white hover:bg-gray-50'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {action.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }